spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:mem:firstdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2

SECRET_KEY: 58703273357638792F423F4528472B4B6250655368566D597133743677397A24