spring:
  config:
    import: optional:file:.env[.properties]

  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:mem:firstdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2

  jwt:
    secret: ${SECRET_KEY_JWT}